// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;

/**
 * Event Args that contains information on a selected menu item
 * TODO simpler access to necessary fields.
 **/
public class MenuItemEventArg : EventArgs
{

}


